#ifndef _ZIBI_MACROS_H
#define _ZIBI_MACROS_H

// This looks incredibly dumb but we need to force expressions to evaluate.

asm (
".macro zibi.beqi rs1 imm label\n"
".if (\\imm) == -1\n"
".insn b BRANCH, 0x2, \\rs1, x0, \\label\n"
".elseif (\\imm) == 0\n"
"beqz \\rs1, \\label\n"
".elseif (\\imm) == 1\n"
".insn b BRANCH, 0x2, \\rs1, x1, \\label\n"
".elseif (\\imm) == 2\n"
".insn b BRANCH, 0x2, \\rs1, x2, \\label\n"
".elseif (\\imm) == 3\n"
".insn b BRANCH, 0x2, \\rs1, x3, \\label\n"
".elseif (\\imm) == 4\n"
".insn b BRANCH, 0x2, \\rs1, x4, \\label\n"
".elseif (\\imm) == 5\n"
".insn b BRANCH, 0x2, \\rs1, x5, \\label\n"
".elseif (\\imm) == 6\n"
".insn b BRANCH, 0x2, \\rs1, x6, \\label\n"
".elseif (\\imm) == 7\n"
".insn b BRANCH, 0x2, \\rs1, x7, \\label\n"
".elseif (\\imm) == 8\n"
".insn b BRANCH, 0x2, \\rs1, x8, \\label\n"
".elseif (\\imm) == 9\n"
".insn b BRANCH, 0x2, \\rs1, x9, \\label\n"
".elseif (\\imm) == 10\n"
".insn b BRANCH, 0x2, \\rs1, x10, \\label\n"
".elseif (\\imm) == 11\n"
".insn b BRANCH, 0x2, \\rs1, x11, \\label\n"
".elseif (\\imm) == 12\n"
".insn b BRANCH, 0x2, \\rs1, x12, \\label\n"
".elseif (\\imm) == 13\n"
".insn b BRANCH, 0x2, \\rs1, x13, \\label\n"
".elseif (\\imm) == 14\n"
".insn b BRANCH, 0x2, \\rs1, x14, \\label\n"
".elseif (\\imm) == 15\n"
".insn b BRANCH, 0x2, \\rs1, x15, \\label\n"
".elseif (\\imm) == 16\n"
".insn b BRANCH, 0x2, \\rs1, x16, \\label\n"
".elseif (\\imm) == 17\n"
".insn b BRANCH, 0x2, \\rs1, x17, \\label\n"
".elseif (\\imm) == 18\n"
".insn b BRANCH, 0x2, \\rs1, x18, \\label\n"
".elseif (\\imm) == 19\n"
".insn b BRANCH, 0x2, \\rs1, x19, \\label\n"
".elseif (\\imm) == 20\n"
".insn b BRANCH, 0x2, \\rs1, x20, \\label\n"
".elseif (\\imm) == 21\n"
".insn b BRANCH, 0x2, \\rs1, x21, \\label\n"
".elseif (\\imm) == 22\n"
".insn b BRANCH, 0x2, \\rs1, x22, \\label\n"
".elseif (\\imm) == 23\n"
".insn b BRANCH, 0x2, \\rs1, x23, \\label\n"
".elseif (\\imm) == 24\n"
".insn b BRANCH, 0x2, \\rs1, x24, \\label\n"
".elseif (\\imm) == 25\n"
".insn b BRANCH, 0x2, \\rs1, x25, \\label\n"
".elseif (\\imm) == 26\n"
".insn b BRANCH, 0x2, \\rs1, x26, \\label\n"
".elseif (\\imm) == 27\n"
".insn b BRANCH, 0x2, \\rs1, x27, \\label\n"
".elseif (\\imm) == 28\n"
".insn b BRANCH, 0x2, \\rs1, x28, \\label\n"
".elseif (\\imm) == 29\n"
".insn b BRANCH, 0x2, \\rs1, x29, \\label\n"
".elseif (\\imm) == 30\n"
".insn b BRANCH, 0x2, \\rs1, x30, \\label\n"
".elseif (\\imm) == 31\n"
".insn b BRANCH, 0x2, \\rs1, x31, \\label\n"
".else\n"
".error \"Zibi immediate out of range\"\n"
".endif\n"
".endm\n"
);


asm (
".macro zibi.bnei rs1 imm label\n"
".if (\\imm) == -1\n"
".insn b BRANCH, 0x3, \\rs1, x0, \\label\n"
".elseif (\\imm) == 0\n"
"bnez \\rs1, \\label\n"
".elseif (\\imm) == 1\n"
".insn b BRANCH, 0x3, \\rs1, x1, \\label\n"
".elseif (\\imm) == 2\n"
".insn b BRANCH, 0x3, \\rs1, x2, \\label\n"
".elseif (\\imm) == 3\n"
".insn b BRANCH, 0x3, \\rs1, x3, \\label\n"
".elseif (\\imm) == 4\n"
".insn b BRANCH, 0x3, \\rs1, x4, \\label\n"
".elseif (\\imm) == 5\n"
".insn b BRANCH, 0x3, \\rs1, x5, \\label\n"
".elseif (\\imm) == 6\n"
".insn b BRANCH, 0x3, \\rs1, x6, \\label\n"
".elseif (\\imm) == 7\n"
".insn b BRANCH, 0x3, \\rs1, x7, \\label\n"
".elseif (\\imm) == 8\n"
".insn b BRANCH, 0x3, \\rs1, x8, \\label\n"
".elseif (\\imm) == 9\n"
".insn b BRANCH, 0x3, \\rs1, x9, \\label\n"
".elseif (\\imm) == 10\n"
".insn b BRANCH, 0x3, \\rs1, x10, \\label\n"
".elseif (\\imm) == 11\n"
".insn b BRANCH, 0x3, \\rs1, x11, \\label\n"
".elseif (\\imm) == 12\n"
".insn b BRANCH, 0x3, \\rs1, x12, \\label\n"
".elseif (\\imm) == 13\n"
".insn b BRANCH, 0x3, \\rs1, x13, \\label\n"
".elseif (\\imm) == 14\n"
".insn b BRANCH, 0x3, \\rs1, x14, \\label\n"
".elseif (\\imm) == 15\n"
".insn b BRANCH, 0x3, \\rs1, x15, \\label\n"
".elseif (\\imm) == 16\n"
".insn b BRANCH, 0x3, \\rs1, x16, \\label\n"
".elseif (\\imm) == 17\n"
".insn b BRANCH, 0x3, \\rs1, x17, \\label\n"
".elseif (\\imm) == 18\n"
".insn b BRANCH, 0x3, \\rs1, x18, \\label\n"
".elseif (\\imm) == 19\n"
".insn b BRANCH, 0x3, \\rs1, x19, \\label\n"
".elseif (\\imm) == 20\n"
".insn b BRANCH, 0x3, \\rs1, x20, \\label\n"
".elseif (\\imm) == 21\n"
".insn b BRANCH, 0x3, \\rs1, x21, \\label\n"
".elseif (\\imm) == 22\n"
".insn b BRANCH, 0x3, \\rs1, x22, \\label\n"
".elseif (\\imm) == 23\n"
".insn b BRANCH, 0x3, \\rs1, x23, \\label\n"
".elseif (\\imm) == 24\n"
".insn b BRANCH, 0x3, \\rs1, x24, \\label\n"
".elseif (\\imm) == 25\n"
".insn b BRANCH, 0x3, \\rs1, x25, \\label\n"
".elseif (\\imm) == 26\n"
".insn b BRANCH, 0x3, \\rs1, x26, \\label\n"
".elseif (\\imm) == 27\n"
".insn b BRANCH, 0x3, \\rs1, x27, \\label\n"
".elseif (\\imm) == 28\n"
".insn b BRANCH, 0x3, \\rs1, x28, \\label\n"
".elseif (\\imm) == 29\n"
".insn b BRANCH, 0x3, \\rs1, x29, \\label\n"
".elseif (\\imm) == 30\n"
".insn b BRANCH, 0x3, \\rs1, x30, \\label\n"
".elseif (\\imm) == 31\n"
".insn b BRANCH, 0x3, \\rs1, x31, \\label\n"
".else\n"
".error \"Zibi immediate out of range\"\n"
".endif\n"
".endm\n"
);

#endif