#!/usr/bin/env python3

import argparse
import os
import shlex
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor

args = sys.argv[1:]

parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument("tests", nargs="*", help="List of tests to run. Empty to run all tests. Each test corresponds to one C file.")
parser.add_argument("--vcd", action="store_true", help="Pass --vcd flag to simulator, to generate waveform dumps.")
parser.add_argument("--tb", default="../tb_verilator/tb", help="Pass tb executable to run tests.")
parser.add_argument("--tbarg", action="append", default=[], help="Extra argument to pass to tb executable. Can pass --tbarg=xxx multiple times to pass multiple arguments.")
parser.add_argument("--postcmd", action="append", default=[], help="Add a command to run post-simulation, e.g. log file processing. The string TEST is expanded to the test result file name, minus any file extensions.")
parser.add_argument("--build-dir", help="Add a suffix to the build directory name, e.g. for different ISA variants")
parser.add_argument("-j", type=int, default=None, help="Number of parallel jobs (default = CPU count).")
parser.add_argument("--march", default="rv32imac_zicsr_zifencei_zba_zbb_zbkb_zbs")
parser.add_argument("--no-tb-build", action="store_true")
parser.epilog = """
Example command lines:

Run all tests:
./runtests

Just run hello world, and generate waves:
./runtests hello_world --vcd

(The last run test is always softlinked as "waves.vcd". You can view it in
gtkwave using the default wave config, "waves.gtkw".)

Run under rvcpp, enable instruction tracing, and post-process log using disassembly:
./runtests --tb ../rvcpp/rvcpp --tbarg=--trace --postcmd="../rvcpp/scripts/annotate_trace.py TEST.log TEST_annotated.log -d TEST.dis"
"""
args = parser.parse_args()

testlist = args.tests

if len(testlist) > 0:
	# This happens a lot when autocomplete is used:
	for i, n in enumerate(testlist):
		if n.endswith(".c"):
			testlist[i] = n[:-2]
else:
	testlist = []
	for path in os.listdir():
		if os.path.isfile(path) and path.endswith(".c"):
			testlist.append(path[:-2])

testlist = sorted(testlist)

if not args.no_tb_build:
	tb_dir = os.path.join(*os.path.split(os.path.abspath(args.tb))[:-1])
	tb_build_ret = subprocess.run(
		["make", "-C", tb_dir, "all"],
		timeout=300
	)
	if tb_build_ret.returncode != 0:
		sys.exit("Failed.")

all_passed = True

if args.build_dir is None:
	build_dir = "tmp"
else:
	build_dir = f"tmp-{args.build_dir}"

# Returns: (build stderr, status message, pass bool).
def run_test(test):
	failed = False
	build_err = ""
	test_build_ret = subprocess.run(
		["make", f"APP={test}", f"TMP_PREFIX={build_dir}/", f"MARCH={args.march}", f"{build_dir}/{test}.bin"],
		stdout=subprocess.DEVNULL,
		stderr=subprocess.PIPE
	)
	if test_build_ret.returncode != 0:
		build_err = test_build_ret.stderr.decode("utf-8", errors="replace").strip()
		status = "\033[33m[MK ERR]\033[39m"
		failed = True

	if not failed:
		cmdline = [args.tb, "--bin", f"{build_dir}/{test}.bin", "--cycles", "1000000"]
		if args.vcd:
			cmdline += ["--vcd", f"{build_dir}/{test}.vcd"]
		cmdline += args.tbarg
		cmdline += ["--logfile", f"{build_dir}/{test}.log"]

		try:
			test_run_ret = subprocess.run(
				cmdline,
				timeout = 10
			)
		except subprocess.TimeoutExpired:
			status = "\033[31m[TIMOUT]\033[39m"
			failed = True

	# Testbench itself should always exit successfully.
	if not failed:
		if test_run_ret.returncode != 0:
			status = "Negative return code from testbench!"
			failed = True

	# Pass if the program under test has zero exit code AND its output matches
	# the expected output (if there is an expected_output file)

	if not failed:
		output_lines = open(f"{build_dir}/{test}.log", "rb").read().decode("utf-8").strip().splitlines()
		returncode = -1
		if len(output_lines) >= 2:
			exit_line = output_lines[-2]
			if exit_line.startswith("CPU requested halt"):
				try:
					returncode = int(exit_line.split(" ")[-1])
				except:
					pass
		if returncode != 0:
			status = "\033[31m[BADRET]\033[39m"
			failed = True

	if not failed:
		test_src = open(f"{test}.c").read()
		if "/*EXPECTED-OUTPUT" in test_src:
			good_output = True
			try:
				expected_start = test_src.find("/*EXPECTED-OUTPUT")
				expected_end = test_src.find("*/", expected_start)
				expected_lines = test_src[expected_start:expected_end + 1].splitlines()[1:-1]
				while expected_lines[0].strip() == "":
					del expected_lines[0]
				while expected_lines[-1].strip() == "":
					del expected_lines[-1]

				# Allow single-line comments within the expected output, in case some of
				# the output needs explanation inline in the test source. If the line is
				# empty after stripping comments, still don't remove the line.
				for i, l in enumerate(expected_lines):
					if "//" in l:
						expected_lines[i] = l.split("//")[0].rstrip()

				# Drop last two lines, which should just be tb output (checked in BADRET)
				output_lines = output_lines[:-2]
				while output_lines[0].strip() == "":
					del output_lines[0]
				while output_lines[-1].strip() == "":
					del output_lines[-1]

				if expected_lines != output_lines:
					good_output = False
			except:
				good_output = False
			if not good_output:
				status = "\033[31m[BADOUT]\033[39m"
				failed = True

	if not failed:
		status = "\033[32m[PASSED]\033[39m"

	# Post-processing commands are run regardless of success. Their return
	# codes are ignored.
	for postcmd in args.postcmd:
		postcmd = postcmd.replace("TEST", f"{build_dir}/{test}")
		subprocess.run(shlex.split(postcmd))

	return build_err, status, not failed

passed_test_count = 0
njobs = os.cpu_count() if args.j is None else max(1, args.j)
with ThreadPoolExecutor(max_workers=njobs) as pool:
	futures = [pool.submit(run_test, test) for test in testlist]
	# Await and print results in launch order
	for test, future in zip(testlist, futures):
		build_err, status, passed = future.result()
		if build_err: print(build_err)
		print(f"{test:<30}{status}")
		if passed:
			passed_test_count += 1
		else:
			all_passed = False

# When re-running a single test, link VCD as "waves.vcd" for use with generic .gtkw config.
if args.vcd and len(testlist) == 1:
	subprocess.run(f"ln -sf {build_dir}/{testlist[0]}.vcd waves.vcd", shell=True)

print(f"\nPassed: {passed_test_count} out of {len(testlist)}")

sys.exit(not all_passed)


