
== Bus Behaviour

Hazard3 implements one or two AHB5 bus manager ports. <<port-descriptions-1port>> describes the signal-level implementation for a single-ported processor, and <<port-descriptions-2port>> for dual-ported. This section describes their behaviour at a higher level, and the requirements Hazard3 imposes on your bus subsystem.

=== Protocol

Hazard3 implements the AHB5 protocol, as described in the https://documentation-service.arm.com/static/5f91607cf86e16515cdc3b4b[AMBA 5 AHB protocol specification].

=== Single and Dual-port

In a dual-ported processor, loads and stores issue to the D port and instruction fetch issues to the I port. In a single-ported processor, all accesses issue to the single available port.

When the processor experiences internal contention, loads and stores take priority over instruction fetch. The rationale for this behaviour is that stalling a load or store will always increase the number of cycles required to execute a program, but stalling an instruction fetch has no cycle cost if the prefetch buffer is able to cover the gap.

For single-ported implementations it's highly recommended to enable compressed instruction support (<<param-EXTENSION_C>> = `1`). This reduces contention between instruction fetch and load/store, increasing performance.

=== Bursts

Hazard3 never generates bursts. `HTRANS` is always `IDLE` or `NSEQ`; `HBURST` is always `SINGLE`.

=== Alignment

All Hazard3 bus accesses are naturally aligned. That is, address modulo access size is always zero; `HADDR % (1 << HSIZE) == 0` (if `HTRANS` is not `IDLE`). Additionally, instruction fetch is always word-aligned and word-sized.

The Zilsd instructions `ld` and `sd` notionally perform 64-bit accesses, but Hazard3 issues these as pairs of 32-bit accesses over its 32-bit AHB bus. The alignment of each access is still four bytes.

[[section-memory-ordering]]
=== Memory Ordering for Loads and Stores

Hazard3 is sequentially consistent for loads and stores when it is connected to a sequentially consistent memory subsystem. Equivalently, if a load/store A is before another load/store B in program order, then A issues before B on the core's AHB5 load/store interface. Architecturally this is a (stronger) subset of the RVTSO memory model.

When executing a `fence` instruction, the core waits for all earlier loads and stores to complete before raising the `fence_d_vld` signal, then waits for `fence_rdy` before issuing more loads or stores. This has no effect on the order the core issues loads and stores to the bus, as they already unconditionally issue in program order. See <<memory-ordering-signals>> for more information about the core's external fence signals.

If a core A executes a `fence` and core B also executes a `fence` at a later time, the memory subsystem must perform any necessary synchronisation to ensure A's load/store accesses issued before A's fence are observed by B's load/store accesses issued after B's fence. Hazard3 does not distinguish different types of data fences: all fences should be treated as `fence rwio, rwio`.

The core is guaranteed not to issue any load or store accesses while `fence_d_vld` is asserted. For a two-ported implementation this is a good opportunity for system hardware to manipulate any logic such as cache controllers attached to the core's load/store port. No such guarantee is made for instruction fetch, so in a single-ported implementation you cannot assume based on `fence_d_vld` that the AHB5 port is idle.

=== Memory Ordering for Instruction Fetch

Hazard3 does not order stores before instruction fetch except with an explicit `fence.i` instruction. This instruction waits for in-progress stores to complete, asserts `fence_i_vld`, waits for `fence_rdy`, and then flushes the prefetch buffer to ensure the next instruction data to be executed is fetched after the instruction fence was observed by the system. It is up to the system designer to ensure that the instruction fetch AHB5 port observes earlier writes from the load/store AHB5 port; this may require flushing of external caches.

In system implementations which lack core-local caches it is usually sufficient to ignore the `fence_i_vld` and `fence_d_vld` signals, and tie `fence_rdy` high.


[[section-exclusive-bus-transfers]]
=== Atomic Instructions and Exclusive Transfers

Hazard3 uses AHB5 exclusive transfers as the _mechanism_ to implement the RISC-V atomic instructions from the A extension. Exclusive transfers are described fully in the AHB5 specification, but briefly:

* The core marks a read or write transfer as _exclusive_ by asserting the `HEXCL` signal high during the address phase.
* The interconnect indicates success or failure of the exclusive transfer by driving the `HEXOKAY` signal during the data phase.

See <<port-descriptions>> for a list of all Hazard3 top-level module ports including the `HEXCL` and `HEXOKAY` signals.

AHB5 does not specify in all cases whether the interconnect should return success or failure; these details are usually furnished by architectural specifications like the https://developer.arm.com/documentation/ddi0553/latest/[Armv8-M Architecture Reference Manual] and its discussion of the Local Monitor and Global Monitor rules. There is no Arm document that directly describes the requirements imposed on the interconnect; these requirements must be extrapolated from the architecture rules.

The idea is that an exclusive write by some hart (some _PE_ in Arm parlance) succeeds if and only if it is preceded by a successful exclusive read by the same hart, _and_ there were no other non-exclusive writes or successful exclusive writes to the same reservation granule by other harts since that successful read. This rule guarantees serialisation of read-modify-write sequences formed of exclusive read/write pairs.

Hazard3 maps RISC-V `lr.w` instructions directly to exclusive reads. The `HEXOKAY` status is stored in a local state flag. This is a 1-bit flag which records whether the core believes it has an outstanding reservation on _all of memory_. The system-level interconnect usually tracks reservations with finer granularity to reduce spurious collisions between harts. It is not necessary for Hazard3 itself to track at any finer granularity: this flag represents its private belief about its reservation status, and determines whether it will _attempt_ an exclusive write on an `sc.w`. The ultimate success or failure for all harts is determined by the tracking logic in the interconnect.

RISC-V `sc.w` instructions map to exclusive writes, with a caveat: if the exclusive read success flag is clear, the `sc.w` does not issue to the bus and immediately returns a failure status in register `rd`. If an exclusive write _is_ issued, the `HEXOKAY` status is reported as success or failure in register `rd`. Finally, executing an `sc.w` instruction unconditionally clears the exclusive read success flag. This prevents issuing multiple exclusive writes following a single successful exclusive read.

The exclusive read success flag is also cleared when executing an `mret` instruction. This ensures that successful read-write pairs are atomic with respect to interrupts, and also prevents the switched-to context in a context switch from retiring a reservation belonging to the switched-from context.

RISC-V `amo*.w` instructions do not translate to any single AHB5 bus message, since AHB5 transfers have either read or write direction, not both. Instead, the core issues an exclusive read followed by an exclusive write, implementing the required read-modify-write operation for the given AMO instruction. If the exclusive write fails, the entire sequence is retried. This has the potential for an infinite loop, so if an exclusive _read_ fails (indicating access to an address that does not support exclusives) then the core abandons the sequence and returns a store/AMO access fault exception (`mcause` = `7`).

Connecting Hazard3 to a Global Monitor designed for a Cortex-M system upholds most RISC-V architecture rules. This is a straightforward approach to integrating Hazard3 into existing interconnects, and also allows interoperability between Arm and RISC-V cores sharing the same atomic variables. The sole exception is the RISC-V eventual success guarantee, also known as the _RsrvEventual_ PMA. Cortex-M Global Monitor rules guarantee _global_ progress, i.e. every race has a winner. RISC-V eventuality requires _local_ progress, i.e. each hart cannot be starved forever. One possibility is to bend the Arm architecture rules and add priority boosting after a hart has tried a certain number of times. The other possibility is to simply accept this limitation and document your system as supporting the _RsrvNonEventual_ PMA.

=== Cacheable and Bufferable Attributes

Hazard3 marks all transfers as non-cacheable and non-bufferable using `HPROT[3:2]`. These signals are tied off to constants and are not controllable by software.

All loads are issued to the external bus, even if they alias with a prior store; there is no store-to-load forwarding. All stores are issued to the external bus, even if they alias with a later store; there is no dead store elimination or write merging. Stores are issued immediately to the bus without buffering inside the core.

It is possible to use Hazard3 in systems with caches, but an alternative mechanism must be implemented to control cacheability of accesses. For example, implement multiple mirrors of the cached memory with attributes decoded from the address.

=== Idempotency

Hazard3 expects that all memory used for instruction fetch is read-idempotent. This limitation comes about because PMP execute permissions are checked at the point an instruction is _executed_, not the point it is fetched. This is a deliberate design decision that reduces the logic depth of fetch address generation logic. As a consequence it is possible to trigger reads from arbitrary addresses by jumping to them (though the data returned by that read is discarded if it lacks execute permissions).

You must not permit instruction fetch from IO regions if <<param-U_MODE>> is configured, because this would allow U-mode software to cause IO read side effects on privileged registers by (fatally) jumping to an IO address. This can be enforced in one of two ways:

* For a 2-port processor, do not connect instruction fetch to IO regions. This is already desirable to improve routing and logic complexity.

* For a 1-port processor, filter instruction fetch from IO regions by rejecting transfers if `HPROT[0]` is `0`.

This limitation does not apply to load/store; Hazard3 checks load/store addresses for PMP read/write permissions before issuing the transfer to the bus. However, idempotency is still a concern for instructions which generate multiple bus accesses, namely:

* Zcmp: `cm.push`, `cm.pop`, `cm.popret`, `cm.popretz`
* Zilsd: `ld`, `sd`
* Zclsd: `c.ld`, `c.ldsp`, `c.sd`, `c.sdsp`

An interrupt occurring mid-instruction terminates its execution immediately. When returning from the interrupt, the instruction restarts from the beginning, as there is no provision in RISC-V for saving and restoring the execution progress. Therefore each individual read or write may execute multiple times before the instruction eventually completes uninterrupted. This can cause lost or duplicated data when accessing IO regions. For this reason these instructions should be avoided when accessing non-idempotent memory.

[[section-64-bit-bus-access]]
=== 64-bit Accesses

Hazard3 implements the Zilsd and Zclsd extensions, which perform 64-bit loads and stores to and from pairs of registers. The register pair is always an even register plus the consecutively next higher-numbered register.

64-bit loads and stores are implemented as pairs of 32-bit AHB5 transfers. Since these accesses only require 4-byte alignment, the load/store address can also be 4-byte-aligned, even though it is notionally an 8-byte transfer.

The RISC-V specification does not guarantee the order in which these two writes are issued, and Hazard3 takes advantage of this to simplify fault handling. When the base address register `rs1` is an even-numbered register, the odd-numbered register in the `rd` or `rs2` pair is transferred first. Conversely, when `rs1` is an odd-numbered register, the even register in the pair is transferred first. This ensures that a fault occurring on the second half of an `ld` instruction does not modify `rs1`. It also means that a consecutively-addressed sequence of 64-bit load/stores is not necessarily consecutively addressed on the AHB5 port. When using `ld` and `sd` instructions for IO, ensure that the peripheral is not sensitive to the order of transfers.

