== Custom Extensions

Hazard3 implements a small number of custom extensions. Xh3misa is always included; the remaining custom extensions are only included if the relevant feature flags are set to `1` when instantiating the processor (<<config-parameters-section>>).

The `x` bit in `<<reg-misa>>` is always set, to indicate (at least) the presence of the Xh3misa extension.

[[custom-extension-list-section]]
=== List of Custom Extensions

The complete list of custom extensions is:

* <<extension-xh3misa-section>>: Enumerates all standard and custom extensions implemented by a given Hazard3 core. Includes standard extensions not listed in `<<reg-misa>>`.
* <<extension-xh3irq-section>>: Adds a lightweight, integrated interrupt controller supporting efficient nested interrupt preemption with dynamically configured interrupt priority. Supports up to 512 IRQ inputs. Composable with external controllers like PLIC.
* <<extension-xh3pmpm-section>>: Allows enforcing unlocked PMP regions in M-mode.
* <<extension-xh3power-section>>: Adds a CSR for controlling low-power sleep states, and hint instructions for cooperative sleep in simple SMP systems.
* <<extension-xh3bextm-section>>: Adds two instructions for extracting small contiguous unsigned bitfields.
* <<extension-xh3sfx-section>>: Adds 17 instructions for accelerating single- and half-precision floating point operations with minimal hardware cost.

[[extension-xh3misa-section]]
=== Xh3misa: Hazard3 ISA identification register

This document describes Xh3misa version: 1.0

This extension is enabled by: <<param-CSR_M_MANDATORY>>.

This extension adds the `<<reg-h3.misa>>` CSR. This is an extended version of the standard `<<reg-misa>>` register, capable of enumerating all standard RISC-V extensions (not just the single-letter ones).

It describes presence and absence of extensions using the bitmap format described in the RISC-V C API documentation:

https://github.com/riscv-non-isa/riscv-c-api-doc/blob/main/src/c-api.adoc#extension-bitmask-definitions[https://github.com/riscv-non-isa/riscv-c-api-doc/blob/main/src/c-api.adoc#extension-bitmask-definitions]

This register also lists the versions of any custom Hazard3 extensions which may be present, including Xh3misa itself. For more details see the description of the `<<reg-h3.misa>>` register.

[[extension-xh3irq-section]]
=== Xh3irq: Hazard3 interrupt controller

This document describes Xh3irq version: 1.0

This extension is enabled by: <<param-EXTENSION_XH3IRQ>>

This lightweight extension controls up to 512 external interrupts, with configurable per-interrupt priority and up to 16 levels of preemption. It adds no new instructions, but several CSRs:

* `<<reg-h3.meiea>>`
* `<<reg-h3.meipa>>`
* `<<reg-h3.meifa>>`
* `<<reg-h3.meipra>>`
* `<<reg-h3.meinext>>`
* `<<reg-h3.meicontext>>`

If this extension is disabled then Hazard3 supports a single external interrupt input (or multiple inputs that it simply ORs together in an uncontrolled fashion), so an external PLIC can be used for standard interrupt support.

This extension is effectively a slightly more complicated way of driving the standard `mip.meip` flag (`<<reg-mip>>`). The RISC-V trap handling CSRs themselves are always completely standard.

[[extension-xh3pmpm-section]]
=== Xh3pmpm: M-mode PMP regions

This document describes Xh3pmpm version: 1.0

This extension is enabled by: <<param-EXTENSION_XH3PMPM>>

This extension adds a new M-mode CSR, `<<reg-h3.pmpcfgm0>>`, which allows a PMP region to be enforced in M-mode without locking the region.

This is useful when the PMP is used for non-security-related purposes such as stack guarding, or trapping and emulation of peripheral accesses.

[[extension-xh3power-section]]
=== Xh3power: Hazard3 power management

This document describes Xh3power version: 1.1

This extension is enabled by: <<param-EXTENSION_XH3POWER>>

This extension adds a new M-mode CSR (`<<reg-h3.msleep>>`), and two new hint instructions, `h3.block` and `h3.unblock`, in the `slt` nop-compatible custom hint space.

The `h3.msleep` CSR controls how deeply the processor sleeps in the WFI sleep state. By default, a WFI is implemented as a normal pipeline stall. By configuring `h3.msleep` appropriately, the processor can gate its own clock when asleep or, with a simple 4-phase req/ack handshake, negotiate with an external power controller for power up/down of external hardware. These options can improve the sleep current at the cost of greater wakeup latency.

The hints allow processors to sleep until woken by other processors in a multiprocessor environment. They are implemented on top of the standard WFI state, which means they interact in the same way with external debug, and benefit from the same deep sleep states in `h3.msleep`.

==== Revisions

Version 1.1 of Xh3power is implemented on Hazard3 stable versions v1.2 onwards. It adds two new conditions for unblock signals:

* The current hart executes an `mret` or `sret` instruction.
* The current hart executes an `h3.unblock` instruction.

In Xh3power 1.0, unblock signals were only produced by neighbouring harts (which may or may not include the current hart, depending on platform implementation) and any additional platform-specified sources of unblock signals.

The two new conditions in Xh3power 1.1 are intended to make `h3.unblock` and `h3.block` easier to reason about when implementing cooperative sleep in SMP systems, because they avoid failure modes where:

* An interrupt or interrupt-initiated context switch accidentally swallows an unblock signal.
* Code behaves differently when the producer and consumer of the unblock signal migrate between cores.

Code written against version 1.0 of this extension is generally compatible with version 1.1, because `h3.block` is a NOP-compatible hint for the hart to sleep, and is usually used inside polling loops that detect early wake-up. However, code relying on the new conditions introduced in Xh3power 1.1 may be prone to unbounded sleep (lockup) on Xh3power 1.0.

[[h3.block-instruction]]
==== h3.block

Enter a WFI sleep state until either an unblock signal is received, or an interrupt is asserted that would cause a WFI to exit.

If an unblock signal has been received in the time since the last `h3.block`, this instruction executes as a `nop`, and the hart does not enter the sleep state. Conceptually, the sleep state falls through immediately because the corresponding unblock signal has already been received.

If `<<reg-mstatus>>.tw` is set, attempting to execute this instruction in privilege modes lower than M-mode will generate an illegal instruction exception.

An unblock signal is received when:

* A neighbouring hart (the exact definition of _neighbouring_ being left to the implementer) executes an `h3.unblock` instruction. This is signalled by a pulse on the `unblock_in` input (<<power-control-signals>>).
* Any other platform-defined event, signalled by a pulse on the `unblock_in` input.
* (Xh3power 1.1 and later) The current hart executes an `mret` or `sret` instruction.
* (Xh3power 1.1 and later) The current hart executes an `h3.unblock` instruction.

`h3.block` allows the core to remain mostly idle in what would otherwise be a busy wait loop. The unblock conditions are designed to be overly broad (causing additional wakeups) rather than overly narrow (causing permanent sleep). When the core wakes, you must check whether the expected wakeup condition is met, and loop if it isn't. As a rule of thumb: write your code in a way that would still be correct if `h3.block` was replaced with a NOP.

This instruction is encoded as `slt x0, x0, x0`, which is part of the custom nop-compatible hint encoding space.

Example C macro:

----
#define __h3_block() asm ("slt x0, x0, x0")
----

Example assembly macro:

----
.macro h3.block
    slt x0, x0, x0
.endm
----

[[h3.unblock-instruction]]
==== h3.unblock

Post an unblock signal to other harts in the system. For example, to notify another processor that a work queue is now nonempty. Also post an unblock signal to the current hart.

If `<<reg-mstatus>>.tw` is set, attempting to execute this instruction in privilege modes lower than M-mode will generate an illegal instruction exception.

This instruction is encoded as `slt x0, x0, x1`, which is part of the custom nop-compatible hint encoding space.

Example C macro:

----
#define __h3_unblock() asm ("slt x0, x0, x1")
----

Example assembly macro:

----
.macro h3.unblock
    slt x0, x0, x1
.endm
----

==== Latching Behaviour

An unblock signal sets an internal state bit. `h3.block` sleeps until this state bit is set, then atomically wakes and clears the state bit. To understand why this latching behaviour is necessary, consider this program executing on two harts:

----
    // Push message to other core
    sw a0, FIFO_TX_OFFSET(a1)
    // Notify other core of message
    h3.unblock

    // Wait for new messages in receiving FIFO
1:
    h3.block
    lw a0, FIFO_RX_VALID_OFFSET(a1)
    beqz a0, 1b

    // Read message
    lw a0, FIFO_RX_OFFSET(a1)
----

Suppose the latching behaviour was not implemented, and `h3.block` was specified as: "sleep until an unblock signal is received". Both cores would send a signal, and then both cores would wait for a signal. No such signal would arrive, because the two cores would both already be asleep, so the system would lock up.

[[extension-xh3bextm-section]]
=== Xh3bextm: Hazard3 Bit Extract Multiple

This document describes Xh3bextm version: 1.0

This extension is enabled by: <<param-EXTENSION_XH3BEXTM>>

This is a small extension with multi-bit versions of the "bit extract" instructions from Zbs, used for extracting small, contiguous bit fields.

==== h3.bextm

"Bit extract multiple", a multi-bit version of the `bext` instruction from Zbs. Perform a right-shift followed by a mask of 1-8 LSBs.

Encoding (R-type):

[cols="10h,20,20,~", options="header"]
|===
| Bits  | Name          | Value      | Description
| 31:29 | `funct7[6:4]` | `0b000`    | RES0
| 28:26 | `size`        | -          | Number of ones in mask, values 0->7 encode 1->8 bits.
| 25    | `funct7[0]`   | `0b0`      | RES0, because aligns with `shamt[5]` of potential RV64 version of `h3.bextmi`
| 24:20 | `rs2`         | -          | Source register 2 (shift amount)
| 19:15 | `rs1`         | -          | Source register 1
| 14:12 | `funct3`      | `0b000`    | `h3.bextm`
| 11:7  | `rd`          | -          | Destination register
| 6:0   | `opc`         | `0b0001011`| custom0 opcode
|===

Example C macro (using GCC statement expressions):

----
// nbits must be a constant expression
#define __h3_bextm(nbits, rs1, rs2) ({\
    uint32_t __h3_bextm_rd; \
    asm (".insn r 0x0b, 0, %3, %0, %1, %2"\
        : "=r" (__h3_bextm_rd) \
        : "r" (rs1), "r" (rs2), "i" ((((nbits) - 1) & 0x7) << 1)\
    ); \
    __h3_bextm_rd; \
})
----

Example assembly macro:

----
// rd = (rs1 >> rs2[4:0]) & ~(-1 << nbits)
.macro h3.bextm rd rs1 rs2 nbits
.if (\nbits < 1) || (\nbits > 8)
.err
.endif
#if NO_HAZARD3_CUSTOM
    srl  \rd, \rs1, \rs2
    andi \rd, \rd, ((1 << \nbits) - 1)
#else
.insn r 0x0b, 0x0, (((\nbits - 1) & 0x7 ) << 1), \rd, \rs1, \rs2
#endif
.endm
----

==== h3.bextmi


Immediate variant of `h3.bextm`.

Encoding (I-type):

[cols="10h,20,20,~", options="header"]
|===
| Bits  | Name          | Value      | Description
| 31:29 | `imm[11:9]`   | `0b000`    | RES0
| 28:26 | `size`        | -          | Number of ones in mask, values 0->7 encode 1->8 bits.
| 25    | `imm[5]`      | `0b0`      | RES0, for potential future RV64 version
| 24:20 | `shamt`       | -          | Shift amount, 0 through 31
| 19:15 | `rs1`         | -          | Source register 1
| 14:12 | `funct3`      | `0b100`    | `h3.bextmi`
| 11:7  | `rd`          | -          | Destination register
| 6:0   | `opc`         | `0b0001011`| custom0 opcode
|===

Example C macro (using GCC statement expressions):

----
// nbits and shamt must be constant expressions
#define __h3_bextmi(nbits, rs1, shamt) ({\
    uint32_t __h3_bextmi_rd; \
    asm (".insn i 0x0b, 0x4, %0, %1, %2"\
        : "=r" (__h3_bextmi_rd) \
        : "r" (rs1), "i" ((((nbits) - 1) & 0x7) << 6 | ((shamt) & 0x1f)) \
    ); \
    __h3_bextmi_rd; \
})
----

Example assembly macro:

----
// rd = (rs1 >> shamt) & ~(-1 << nbits)
.macro h3.bextmi rd rs1 shamt nbits
.if (\nbits < 1) || (\nbits > 8)
.err
.endif
.if (\shamt < 0) || (\shamt > 31)
.err
.endif
#if NO_HAZARD3_CUSTOM
    srli \rd, \rs1, \shamt
    andi \rd, \rd, ((1 << \nbits) - 1)
#else
.insn i 0x0b, 0x4, \rd, \rs1, (\shamt & 0x1f) | (((\nbits - 1) & 0x7 ) << 6)
#endif
.endm
----

[[extension-xh3sfx-section]]
=== Xh3sfx: Hazard3 Soft Float Acceleration

This document describes Xh3sfx version: 1.0

This extension is enabled by: <<param-EXTENSION_XH3SFX>>.

Xh3sfx is a lightweight extension for accelerating calculations with IEEE 754 binary32 and binary16 formats, also known as single-precision and half-precision floating point. It focuses on packing, unpacking and rounding of floating-point values; the actual floating-point computation uses the existing integer instructions. It adds no architectural state, therefore there is no overhead for interrupts.

==== Data Formats

The binary16 format (half precision) is defined as follows:

* 1 sign bit, bit `15`.
* 5 exponent bits, stored in bits `14` to `10`.
* 10 significand bits, stored in bits `9` to `0`.
* Exponent bias of 15.

The binary32 format (single precision) is defined as follows:

* 1 sign bit, bit `31`.
* 8 exponent bits, stored in bits `30` to `23`.
* 23 significand bits, stored in bits `22` to `0`.
* Exponent bias of 127.

Unpacked significands are represented with the Q3.29 format (or simply `q3`), which is defined as follows:

* Two's complement.
* 3 integer bits (including sign), stored in bits `31` to `29`.
* 29 fractional bits, stored in bits `28` to `0`.

This fixed-point format represents real numbers in the interval -4 ≤ _x_ < 4, which is sufficient for addition of IEEE 754 significands normalised to the interval 1 ≤ |_x_| < 2. It also has sufficient fractional bits that a 32 × 32 -> 64-bit multiply (`mul; mulh`) leaves the guard and round bits, plus space for the sticky bit, in the upper half of the result.

In some cases, such as converting unsigned integers to floating point numbers, it can be useful to interpret integer registers as U3.29 format (or simply `u3`). This is the same as Q3.29, except it is unsigned. It represents real numbers in the interval 0 ≤ _x_ < 8.

==== h3.funpackq3.s

Unpack significand from single-precision to Q3.29. The result is in the range `0xc0000040` through `0x3fffffc0` inclusive, which is approximately -2 through +2. This is equivalent to the following C code:

----
uint32_t h3_funpackq3_s(uint32_t rs1) {
    uint32_t tmp0 = rs1 << 9;
    uint32_t tmp1 = tmp0 >> 3;
    uint32_t tmp2 = tmp1 | (1u << 29);
    return rs1 & (1u << 31) ? -tmp2 : tmp2;
}
----

The result is a function only of the sign and significand bits of `rs1`. It does not depend on the exponent. Therefore the implicit one is set even if the exponent is all-zeroes.

NOTE: The expectation is that zero exponents are checked with `h3.fcheck2e.s` and handled as a special case to enforce consistent flush-to-zero semantics on both inputs and outputs. Another (non-IEEE-compliant) option is to treat exponent `0` as the next normal exponent below `1`, which slightly extends the range without having to handle subnormals.

Encoding (R-type):

[cols="10h,20,20,~", options="header"]
|===
| Bits  | Name     | Value        | Description
| 31:25 | `funct7` | `0b1000000`  | `h3.funpackq3.s`
| 24:20 | -        | `0b00000`    | RES0
| 19:15 | `rs1`    | -            | Source register 1
| 14:12 | `funct3` | `0b001`      | Xh3sfx R-type space
| 11:7  | `rd`     | -            | Destination register
| 6:0   | `opc`    | `0b0001011`  | custom0 opcode
|===

Example C macro (using GCC statement expressions):

----
#define __h3_funpackq3_s(rs1) ({\
    uint32_t __rd; \
    asm (".insn r 0x0b, 0x1, 0x40, %0, %1, zero"\
        : "=r" (__rd) \
        : "r" (rs1) \
    ); \
    __rd; \
})
----

==== h3.funpackq3.h

Unpack significand from half-precision to Q3.29. The result is in the range `0xc0040000` through `0x3ffc0000` inclusive, which is approximately -2 through +2. This is equivalent to the following C code:

----
uint32_t h3_funpackq3_h(uint32_t rs1) {
    uint32_t tmp0 = rs1 << 22;
    uint32_t tmp1 = tmp0 >> 3;
    uint32_t tmp2 = tmp1 | (1u << 29);
    return rs1 & (1u << 15) ? -tmp2 : tmp2;
}
----


The result is a function only of the sign and significand bits of `rs1`. It does not depend on the exponent. Therefore the implicit one is set even if the exponent is all-zeroes.

NOTE: The expectation is that zero exponents are checked with `h3.fcheck2e.h` and handled as a special case to enforce consistent flush-to-zero semantics on both inputs and outputs. Another (non-IEEE-compliant) option is to treat exponent `0` as the next normal exponent below `1`, which slightly extends the range without having to handle subnormals.

Encoding (R-type):

[cols="10h,20,20,~", options="header"]
|===
| Bits  | Name     | Value        | Description
| 31:25 | `funct7` | `0b0000000`  | `h3.funpackq3.h`
| 24:20 | -        | `0b00000`    | RES0
| 19:15 | `rs1`    | -            | Source register 1
| 14:12 | `funct3` | `0b001`      | Xh3sfx R-type space
| 11:7  | `rd`     | -            | Destination register
| 6:0   | `opc`    | `0b0001011`  | custom0 opcode
|===

Example C macro (using GCC statement expressions):

----
#define __h3_funpackq3_h(rs1) ({\
    uint32_t __rd; \
    asm (".insn r 0x0b, 0x1, 0x00, %0, %1, zero"\
        : "=r" (__rd) \
        : "r" (rs1) \
    ); \
    __rd; \
})
----

==== h3.funpacku3.s

Unpack significand from single-precision to U3.29. The result is in the range `0x00000000` through `0x3fffffc0` inclusive, which is approximately 0 through +2. This is equivalent to the following C code:

----
uint32_t h3_funpacku3_s(uint32_t rs1) {
    uint32_t tmp0 = rs1 << 9;
    uint32_t tmp1 = tmp0 >> 3;
    return tmp1 | (1u << 29);
}
----

The result is a function only of the significand bits of `rs1`. It does not depend on the exponent. Therefore the implicit one is set even if the exponent is all-zeroes.

Encoding (R-type):

[cols="10h,20,20,~", options="header"]
|===
| Bits  | Name     | Value        | Description
| 31:25 | `funct7` | `0b1000001`  | `h3.funpacku3.s`
| 24:20 | -        | `0b00000`    | RES0
| 19:15 | `rs1`    | -            | Source register 1
| 14:12 | `funct3` | `0b001`      | Xh3sfx R-type space
| 11:7  | `rd`     | -            | Destination register
| 6:0   | `opc`    | `0b0001011`  | custom0 opcode
|===

Example C macro (using GCC statement expressions):

----
#define __h3_funpacku3_s(rs1) ({\
    uint32_t __rd; \
    asm (".insn r 0x0b, 0x1, 0x41, %0, %1, zero"\
        : "=r" (__rd) \
        : "r" (rs1) \
    ); \
    __rd; \
})
----

==== h3.funpacku3.h

Unpack significand from half-precision to U3.29. The result is in the range `0x00000000` through `0x3ffc0000` inclusive, which is approximately 0 through +2. This is equivalent to the following C code:

----
uint32_t h3_funpacku3_h(uint32_t rs1) {
    uint32_t tmp0 = rs1 << 22;
    uint32_t tmp1 = tmp0 >> 3;
    return tmp1 | (1u << 29);
}
----

The result is a function only of the significand bits of `rs1`. It does not depend on the exponent. Therefore the implicit one is set even if the exponent is all-zeroes.

Encoding (R-type):

[cols="10h,20,20,~", options="header"]
|===
| Bits  | Name     | Value        | Description
| 31:25 | `funct7` | `0b0000001`  | `h3.funpacku3.h`
| 24:20 | -        | `0b00000`    | RES0
| 19:15 | `rs1`    | -            | Source register 1
| 14:12 | `funct3` | `0b001`      | Xh3sfx R-type space
| 11:7  | `rd`     | -            | Destination register
| 6:0   | `opc`    | `0b0001011`  | custom0 opcode
|===

Example C macro (using GCC statement expressions):

----
#define __h3_funpacku3_h(rs1) ({\
    uint32_t __rd; \
    asm (".insn r 0x0b, 0x1, 0x01, %0, %1, zero"\
        : "=r" (__rd) \
        : "r" (rs1) \
    ); \
    __rd; \
})
----

==== h3.fcheck2e.s

Check two single-precision biased exponents for special cases. Returns `1` if either `rs1[7:0]` or `rs2[7:0]` is equal to either `0` or `255`. Otherwise returns `0`.

Operand bits `31:8` are not checked.

Encoding (R-type):

[cols="10h,20,20,~", options="header"]
|===
| Bits  | Name     | Value        | Description
| 31:25 | `funct7` | `0b1000010`  | `h3.fcheck2e.s`
| 24:20 | `rs2`    | -            | Source register 2
| 19:15 | `rs1`    | -            | Source register 1
| 14:12 | `funct3` | `0b001`      | Xh3sfx R-type space
| 11:7  | `rd`     | -            | Destination register
| 6:0   | `opc`    | `0b0001011`  | custom0 opcode
|===

Example C macro (using GCC statement expressions):

----
#define __h3_fcheck2e_s(rs1, rs2) ({\
    uint32_t __rd; \
    asm (".insn r 0x0b, 0x1, 0x42, %0, %1, %2"\
        : "=r" (__rd) \
        : "r" (rs1), "r" (rs2) \
    ); \
    __rd; \
})
----

==== h3.fcheck2e.h

Check two half-precision biased exponents for special cases. Returns `1` if either `rs1[4:0]` or `rs2[4:0]` is equal to either `0` or `31`. Otherwise returns `0`.

Operand bits `31:5` are not checked.

Encoding (R-type):

[cols="10h,20,20,~", options="header"]
|===
| Bits  | Name     | Value        | Description
| 31:25 | `funct7` | `0b0000010`  | `h3.fcheck2e.h`
| 24:20 | `rs2`    | -            | Source register 2
| 19:15 | `rs1`    | -            | Source register 1
| 14:12 | `funct3` | `0b001`      | Xh3sfx R-type space
| 11:7  | `rd`     | -            | Destination register
| 6:0   | `opc`    | `0b0001011`  | custom0 opcode
|===

Example C macro (using GCC statement expressions):

----
#define __h3_fcheck2e_h(rs1, rs2) ({\
    uint32_t __rd; \
    asm (".insn r 0x0b, 0x1, 0x02, %0, %1, %2"\
        : "=r" (__rd) \
        : "r" (rs1), "r" (rs2) \
    ); \
    __rd; \
})
----

==== h3.fpackrq3.s

Pack rounded significand and exponent into single-precision.

The significand in `rs1` is in Q3.29 format and must be normalised or zero; that is, it must be either:

* In the range -2 < _x_ ≤ -1.
* In the range 1 ≤ _x_ < 2.
* Equal to zero.

The exponent in `rs2` is a signed integer and must be in the range -512 ≤ _x_ ≤ 510. The instruction applies the following steps in sequence:

* If all significant bits of `rs1` are zero, return `+0.f`.
* Take absolute value of `rs1`.
* Round `rs1` to 23 fractional bits; the rounding rule is to-nearest, even on tie.
* If bit 30 of `rs1` is set, shift right by 1 and increment exponent by 1
* If exponent ≤ 0, return `0.f` with input sign
* If exponent ≥ 255, return `inf` with input sign
* Pack sign, exponent and rounded significand, and return

NOTE: The normalisation requirement on `rs1` and the exponent underflow rule have the net effect that subnormal results are flushed to zero, _unless_ they round up to normality when rounded with an unbounded exponent range. This is equivalent to flush on _tininess after rounding_ (IEEE 754-2008  §7.5) and matches AArch64 behaviour with `FPCR.FZ` = `1`, `FPCR.AH` = `1`.

Encoding (R-type):

[cols="10h,20,20,~", options="header"]
|===
| Bits  | Name     | Value        | Description
| 31:25 | `funct7` | `0b1000011`  | `h3.fpackrq3.s`
| 24:20 | `rs2`    | -            | Source register 2
| 19:15 | `rs1`    | -            | Source register 1
| 14:12 | `funct3` | `0b001`      | Xh3sfx R-type space
| 11:7  | `rd`     | -            | Destination register
| 6:0   | `opc`    | `0b0001011`  | custom0 opcode
|===

Example C macro (using GCC statement expressions):

----
#define __h3_fpackrq3_s(rs1, rs2) ({\
    uint32_t __rd; \
    asm (".insn r 0x0b, 0x1, 0x43, %0, %1, %2"\
        : "=r" (__rd) \
        : "r" (rs1), "r" (rs2) \
    ); \
    __rd; \
})
----

==== h3.fpackrq3.h

Pack rounded significand and exponent into half-precision. The packed floating-point result is returned in the 16 LSBs of `rd`, and the sign bit is extended to fill the remaining XLEN - 16 bits.

NOTE: Sign extension up from bit `15` matches the results produced by the standard Zhinx extension, and differs from the NaN boxing scheme used by the Zfh extension.

The significand in `rs1` is in Q3.29 format and must be normalised or zero; that is, it must be either:

* In the range -2 < _x_ ≤ -1.
* In the range 1 ≤ _x_ < 2.
* Equal to zero.

The exponent in `rs2` is a signed integer and must be in the range -512 ≤ _x_ ≤ 510.

NOTE: This exponent range is wider than required for half-precision calculations but is useful when converting from single-precision to half-precision.

The instruction applies the following steps in sequence:

* If all significant bits of `rs1` are zero, return `+0.f`
* Take absolute value of `rs1`
* Round `rs1` to 10 fractional bits; the rounding rule is to-nearest, even on tie.
* If bit 30 of `rs1` is set, shift right by 1 and increment exponent by 1
* If exponent ≤ 0, return `0.f` with input sign
* If exponent ≥ 31, return `inf` with input sign
* Pack sign, exponent and rounded significand, and return

NOTE: The normalisation requirement on `rs1` and the exponent underflow rule have the net effect that subnormal results are flushed to zero, _unless_ they round up to normality when rounded with an unbounded exponent range. This is equivalent to flush on _tininess after rounding_ (IEEE 754-2008  §7.5) and matches AArch64 behaviour with `FPCR.FZ` = `1`, `FPCR.AH` = `1`.

Encoding (R-type):

[cols="10h,20,20,~", options="header"]
|===
| Bits  | Name     | Value        | Description
| 31:25 | `funct7` | `0b0000011`  | `h3.fpackrq3.h`
| 24:20 | `rs2`    | -            | Source register 2
| 19:15 | `rs1`    | -            | Source register 1
| 14:12 | `funct3` | `0b001`      | Xh3sfx R-type space
| 11:7  | `rd`     | -            | Destination register
| 6:0   | `opc`    | `0b0001011`  | custom0 opcode
|===

Example C macro (using GCC statement expressions):

----
#define __h3_fpackrq3_h(rs1, rs2) ({\
    uint32_t __rd; \
    asm (".insn r 0x0b, 0x1, 0x03, %0, %1, %2"\
        : "=r" (__rd) \
        : "r" (rs1), "r" (rs2) \
    ); \
    __rd; \
})
----

==== h3.feadjq3

Calculate exponent adjustment for Q3.29 format. Returns the greatest integer _x_ in the range -30 ≤ _x_ ≤ 2 such that right-shifting `rs1` by this integer produces a Q3.29 value _y_ in the range 1 ≤ |_y_| < 2. Negative values imply a left shift. If `rs1` is zero, the result is -30.

This calculation is equivalent to the following C code:

----
return 2 - __builtin_clz(rs1 < 0 ? -rs1 : rs1);
----

This value can be passed into `h3.ssrasticky` in `rs2` to re-normalise a Q3.29 value in `rs1`. It is also exactly the value which should be added to the floating-point exponent to account for the re-normalisation performed by `h3.ssrasticky`.

Encoding (R-type):

[cols="10h,20,20,~", options="header"]
|===
| Bits  | Name     | Value        | Description
| 31:25 | `funct7` | `0b0000100`  | `h3.feadjq3`
| 24:20 | -        | `0b00000`    | RES0
| 19:15 | `rs1`    | -            | Source register 1
| 14:12 | `funct3` | `0b001`      | Xh3sfx R-type space
| 11:7  | `rd`     | -            | Destination register
| 6:0   | `opc`    | `0b0001011`  | custom0 opcode
|===

Example C macro (using GCC statement expressions):

----
#define __h3_feadjq3(rs1) ({\
    uint32_t __rd; \
    asm (".insn r 0x0b, 0x1, 0x04, %0, %1, zero"\
        : "=r" (__rd) \
        : "r" (rs1) \
    ); \
    __rd; \
})
----

==== h3.feadju3

Calculate exponent adjustment for U3.29 format. Returns the greatest integer _x_ in the range -30 ≤ _x_ ≤ 2 such that right-shifting `rs1` by this integer produces a U3.29 value _y_ in the range 1 ≤ _y_ < 2. Negative values imply a left shift. If `rs1` is zero, the result is -30.

This calculation is equivalent to the following C code:

----
return 2 - __builtin_clz(rs1);
----

This value can be passed into `h3.ssrlsticky` in `rs2` to re-normalise a U3.29 value in `rs1`. It is also exactly the value which should be added to the floating-point exponent to account for the re-normalisation performed by `h3.ssrlsticky`.

Encoding (R-type):

[cols="10h,20,20,~", options="header"]
|===
| Bits  | Name     | Value        | Description
| 31:25 | `funct7` | `0b0000101`  | `h3.feadju3`
| 24:20 | -        | `0b00000`    | RES0
| 19:15 | `rs1`    | -            | Source register 1
| 14:12 | `funct3` | `0b001`      | Xh3sfx R-type space
| 11:7  | `rd`     | -            | Destination register
| 6:0   | `opc`    | `0b0001011`  | custom0 opcode
|===

Example C macro (using GCC statement expressions):

----
#define __h3_feadju3(rs1) ({\
    uint32_t __rd; \
    asm (".insn r 0x0b, 0x1, 0x05, %0, %1, zero"\
        : "=r" (__rd) \
        : "r" (rs1) \
    ); \
    __rd; \
})
----

==== h3.xorsign

Returns `rs1 < 0 ? -rs2 : rs2`.

This conditional negation is useful for making integer right-shifts truncate towards zero instead of towards negative infinity, as shown in the `fixsfsi2` example. It also implements the C `abs()` operation in one instruction, when the same register is passed as `rs1` and `rs2`.

Encoding (R-type):

[cols="10h,20,20,~", options="header"]
|===
| Bits  | Name     | Value        | Description
| 31:25 | `funct7` | `0b0000110`  | `h3.xorsign`
| 24:20 | `rs2`    | -            | Source register 2
| 19:15 | `rs1`    | -            | Source register 1
| 14:12 | `funct3` | `0b001`      | Xh3sfx R-type space
| 11:7  | `rd`     | -            | Destination register
| 6:0   | `opc`    | `0b0001011`  | custom0 opcode
|===

Example C macro (using GCC statement expressions):

----
#define __h3_xorsign(rs1, rs2) ({\
    uint32_t __rd; \
    asm (".insn r 0x0b, 0x1, 0x06, %0, %1, %2"\
        : "=r" (__rd) \
        : "r" (rs1), "r" (rs2) \
    ); \
    __rd; \
})
----

==== h3.ssla

Shift signed-left, arithmetic. `rs2` is a signed integer wrapped to the range -512 ≤ _x_ ≤ 511. The cases are:

* -512 ≤ _x_ ≤ -32: result is all-sign.
* -32 < _x_ < 0: result is `rs1 >> -rs2[4:0]` (arithmetic right shift).
* 0 ≤ _x_ < 32: result is `rs1 << rs2[4:0]`.
* 32 ≤ _x_ ≤ 511: result is all-zeroes.

Encoding (R-type):

[cols="10h,20,20,~", options="header"]
|===
| Bits  | Name     | Value        | Description
| 31:25 | `funct7` | `0b0101100`  | `h3.ssla`
| 24:20 | `rs2`    | -            | Source register 2
| 19:15 | `rs1`    | -            | Source register 1
| 14:12 | `funct3` | `0b001`      | Xh3sfx R-type space
| 11:7  | `rd`     | -            | Destination register
| 6:0   | `opc`    | `0b0001011`  | custom0 opcode
|===

Example C macro (using GCC statement expressions):

----
#define __h3_ssla(rs1, rs2) ({\
    uint32_t __rd; \
    asm (".insn r 0x0b, 0x1, 0x2c, %0, %1, %2"\
        : "=r" (__rd) \
        : "r" (rs1), "r" (rs2) \
    ); \
    __rd; \
})
----

==== h3.ssll

Shift signed-left, logical. `rs2` is a signed integer wrapped to the range -512 ≤ _x_ ≤ 511. The cases are:

* -512 ≤ _x_ ≤ -32: result is all-zeroes.
* -32 < _x_ < 0: result is `rs1 >> -rs2[4:0]` (logical right shift).
* 0 ≤ _x_ < 32: result is `rs1 << rs2[4:0]`.
* 32 ≤ _x_ ≤ 511: result is all-zeroes.

Encoding (R-type):

[cols="10h,20,20,~", options="header"]
|===
| Bits  | Name     | Value        | Description
| 31:25 | `funct7` | `0b0001100`  | `h3.ssll`
| 24:20 | `rs2`    | -            | Source register 2
| 19:15 | `rs1`    | -            | Source register 1
| 14:12 | `funct3` | `0b001`      | Xh3sfx R-type space
| 11:7  | `rd`     | -            | Destination register
| 6:0   | `opc`    | `0b0001011`  | custom0 opcode
|===

Example C macro (using GCC statement expressions):

----
#define __h3_ssll(rs1, rs2) ({\
    uint32_t __rd; \
    asm (".insn r 0x0b, 0x1, 0x0c, %0, %1, %2"\
        : "=r" (__rd) \
        : "r" (rs1), "r" (rs2) \
    ); \
    __rd; \
})
----

==== h3.ssra

Shift signed-right, arithmetic. `rs2` is a signed integer wrapped to the range -512 ≤ _x_ ≤ 511. The cases are:

* -512 ≤ _x_ ≤ -32: result is all-zeroes.
* -32 < _x_ < 0: result is `rs1 << -rs2[4:0]`.
* 0 ≤ _x_ < 32: result is `rs1 >> rs2[4:0]` (arithmetic right shift).
* 32 ≤ _x_ ≤ 511: result is all-sign.

Encoding (R-type):

[cols="10h,20,20,~", options="header"]
|===
| Bits  | Name     | Value        | Description
| 31:25 | `funct7` | `0b0101000`  | `h3.ssra`
| 24:20 | `rs2`    | -            | Source register 2
| 19:15 | `rs1`    | -            | Source register 1
| 14:12 | `funct3` | `0b001`      | Xh3sfx R-type space
| 11:7  | `rd`     | -            | Destination register
| 6:0   | `opc`    | `0b0001011`  | custom0 opcode
|===

Example C macro (using GCC statement expressions):

----
#define __h3_ssra(rs1, rs2) ({\
    uint32_t __rd; \
    asm (".insn r 0x0b, 0x1, 0x28, %0, %1, %2"\
        : "=r" (__rd) \
        : "r" (rs1), "r" (rs2) \
    ); \
    __rd; \
})
----

==== h3.ssrl

Shift signed-right, logical. `rs2` is a signed integer wrapped to the range -512 ≤ _x_ ≤ 511. The cases are:

* -512 ≤ _x_ ≤ -32: result is all-zeroes.
* -32 < _x_ < 0: result is `rs1 << -rs2[4:0]`.
* 0 ≤ _x_ < 32: result is `rs1 >> rs2[4:0]` (logical right shift).
* 32 ≤ _x_ ≤ 511: result is all-zeroes.

Encoding (R-type):

[cols="10h,20,20,~", options="header"]
|===
| Bits  | Name     | Value        | Description
| 31:25 | `funct7` | `0b0001000`  | `h3.ssrl`
| 24:20 | `rs2`    | -            | Source register 2
| 19:15 | `rs1`    | -            | Source register 1
| 14:12 | `funct3` | `0b001`      | Xh3sfx R-type space
| 11:7  | `rd`     | -            | Destination register
| 6:0   | `opc`    | `0b0001011`  | custom0 opcode
|===

Example C macro (using GCC statement expressions):

----
#define __h3_ssrl(rs1, rs2) ({\
    uint32_t __rd; \
    asm (".insn r 0x0b, 0x1, 0x08, %0, %1, %2"\
        : "=r" (__rd) \
        : "r" (rs1), "r" (rs2) \
    ); \
    __rd; \
})
----

==== h3.ssrasticky

Shift signed-right, arithmetic, with sticky bits collected at LSB. `rs1` is shifted right by a signed amount stored in `rs2[9:0]`. The shift amount is wrapped into the range -512 ≤ _x_ ≤ 511. Positive shift amounts shift to the right, and negative to the left. Bits shifted off the right end of `rs1` are ORed into the LSB.

NOTE: The size of the shift range is chosen to avoid special-case branching when adding numbers with large exponent differences. For addition of normals, the greatest possible exponent difference is 253. For fused multiply-add it may be even larger.

Shifts outside of the range ±31 are handled as follows:

* `rs2[9:0]` ≥ 32 results in all-sign, except for bit `0` of the result, which is the OR of all bits in `rs1`.

* `rs2[9:0]` ≤ -32 results in all-zero.

Encoding (R-type):

[cols="10h,20,20,~", options="header"]
|===
| Bits  | Name     | Value        | Description
| 31:25 | `funct7` | `0b0101010`  | `h3.ssrasticky`
| 24:20 | `rs2`    | -            | Source register 2
| 19:15 | `rs1`    | -            | Source register 1
| 14:12 | `funct3` | `0b001`      | Xh3sfx R-type space
| 11:7  | `rd`     | -            | Destination register
| 6:0   | `opc`    | `0b0001011`  | custom0 opcode
|===

Example C macro (using GCC statement expressions):

----
#define __h3_ssrasticky(rs1, rs2) ({\
    uint32_t __rd; \
    asm (".insn r 0x0b, 0x1, 0x2a, %0, %1, %2"\
        : "=r" (__rd) \
        : "r" (rs1), "r" (rs2) \
    ); \
    __rd; \
})
----

==== h3.ssrlsticky

Shift signed-right, logical, with sticky bits collected at LSB. `rs1` is shifted right by a signed amount stored in `rs2[9:0]`. The shift amount is wrapped into the range -512 ≤ _x_ ≤ 511. Positive shift amounts shift to the right, and negative to the left. Bits shifted off the right end of `rs1` are ORed into the LSB.

Shifts outside of the range ±31 are handled as follows:

* `rs2[9:0]` ≥ 32 results in all-zeroes, except for bit `0` of the result, which is the OR of all bits in `rs1`.

* `rs2[9:0]` ≤ -32 results in all-zeroes.

Encoding (R-type):

[cols="10h,20,20,~", options="header"]
|===
| Bits  | Name     | Value        | Description
| 31:25 | `funct7` | `0b0001010`  | `h3.ssrlsticky`
| 24:20 | `rs2`    | -            | Source register 2
| 19:15 | `rs1`    | -            | Source register 1
| 14:12 | `funct3` | `0b001`      | Xh3sfx R-type space
| 11:7  | `rd`     | -            | Destination register
| 6:0   | `opc`    | `0b0001011`  | custom0 opcode
|===

Example C macro (using GCC statement expressions):

----
#define __h3_ssrlsticky(rs1, rs2) ({\
    uint32_t __rd; \
    asm (".insn r 0x0b, 0x1, 0x0a, %0, %1, %2"\
        : "=r" (__rd) \
        : "r" (rs1), "r" (rs2) \
    ); \
    __rd; \
})
----

[[xh3sfx-examples-section]]
==== Examples

NOTE: The function names in this section follow the conventions for https://gcc.gnu.org/onlinedocs/gccint/Soft-float-library-routines.html[libgcc].

===== Single-precision Add and Subtract

The `h3.fcheck2e.s` instruction and the accompanying branch eliminates any NaN, infinity and (potentially unflushed) zero inputs from the main path. The remainder of the function only needs to deal with normal inputs.

The first `h3.ssrasticky` serves to align the lower-exponent number against the higher-exponent number. The higher-exponent number remains normalised to Q3.29.

The second `h3.ssrasticky` re-aligns the result. The range of possible values for  `h3.feadjq3` here is `1` to `-30`. The value of `-30` only occurs in the case of exact cancellation (i.e. _x_ + -__x__ for some _x_). We actually get the wrong exponent in this case; this is fine since `h3.fpackrq3.s` already handles all-zeroes significand as a special case, in order to produce the _positive_ zero that IEEE 754 requires for exact cancellation.

----
.global __subsf3
.p2align 2
__subsf3:
    binvi a1, a1, 31
.global __addsf3
__addsf3:
    h3.bextmi a2, a0, 23, 8
    h3.bextmi a3, a1, 23, 8
    h3.fcheck2e.s t0, a2, a3
    bnez t0, __addsf_special_exponent
    h3.funpackq3.s a4, a0
    h3.funpackq3.s a5, a1

    bltu a2, a3, __addsf_ye_gt_xe

.macro addsf_core packed_lhs, packed_rhs, sig_lhs, sig_rhs, exp_lhs, exp_rhs
    sub \packed_rhs, \exp_lhs, \exp_rhs
    h3.ssrasticky \packed_lhs, \sig_rhs, \packed_rhs
    add \sig_lhs, \sig_lhs, \packed_lhs
    h3.feadjq3 \packed_lhs, \sig_lhs
    h3.ssrasticky \sig_lhs, \sig_lhs, \packed_lhs
    add \exp_lhs, \exp_lhs, \packed_lhs
    h3.fpackrq3.s a0, \sig_lhs, \exp_lhs
    ret
.endm

__addsf_xe_gte_ye:
    addsf_core a0, a1, a4, a5, a2, a3
.p2align 2
__addsf_ye_gt_xe:
    addsf_core a1, a0, a5, a4, a3, a2

__addsf_special_exponent:
    // Handle special cases...
----

===== Single-precision Multiply

Again, any zeroes and infinities are swiftly eliminated from the main path because these have complex rules in IEEE 754. The main path only deals with multiplication of normals.

It's necessary to collect sticky bits from the low fraction in `a0` _before_ normalising `a4`, to ensure correct handling of a nearly-subnormal result whose fractional bits in `a4` are all zero.

----
.global __mulsf3
.p2align 2
__mulsf3:
    h3.bextmi a2, a0, 23, 8
    h3.bextmi a3, a1, 23, 8
    h3.fcheck2e.s t0, a2, a3
    bnez t0, __mulsf_special_exponent
    h3.funpackq3.s a4, a0
    h3.funpackq3.s a5, a1

    // Multiply Q3.29 x Q3.29 -> Q6.58
    mul a1, a4, a5
    mulh a4, a4, a5
    // Gather sticky bits from low fraction; a4 now effectively Q6.26
    snez a1, a1
    or a4, a4, a1
    // Normalise (shift left by either 2 or 3)
    h3.feadjq3 a0, a4
    h3.ssrasticky a4, a4, a0
    // Calculate new exponent;
    // -127 is for redundant bias, +3 is for Q6 -> Q3 compensation
    add a2, a2, a0
    add a2, a2, a3
    addi a2, a2, -127 + 3
    h3.fpackrq3.s a0, a4, a2
    ret

__mulsf_special_exponent:
    // Handle special cases...
----

===== Convert Single-precision to Half-precision

Most cases are correctly handled by simply unpacking single-precision to Q3.29, adjusting the exponent bias, and re-packing as half-precision. The one troublesome case is a signaling NaN input may have its payload rounded to all-zeroes, producing an infinity. This requires a special case to promote all input NaNs to a canonical quiet NaN.

----
.global __truncsfhf2
__truncsfhf2:
    h3.funpackq3.s a1, a0
    h3.bextmi a2, a0, 23, 8
    li t0, 255
    beq a2, t0, 2f
1:
    addi a2, a2, -127 + 15
    h3.fpackrq3.h a0, a1, a2
    ret
2:
    // Return canonical NaN on NaN input. Use a sign-extended value for
    // consistency with other half-precision results.
    slli a0, a0, 9
    beqz a0, 1b
    li a0, -1
    ret
----

===== Compare Single-precision

Concatenation of exponent and significand is correctly ordered with respect to
magnitude. This is a 31-bit value; converting sign-magnitude to two's complement
gives a fully correctly ordered 32-bit integer.

This doesn't handle NaNs gracefully but, quote libgcc docs, "you should not
rely on this; if NaN is a possibility, use one of the higher-level comparison
functions".

----
.global __fcmpsf2
__fcmpsf2:
    bclri a2, a0, 31
    bclri a3, a1, 31
    h3.xorsign a2, a0, a2
    h3.xorsign a3, a1, a3
    slt a1, a2, a3
    slt a0, a3, a2
    sub a0, a0, a1
    ret
----

===== Convert Single-precision to Signed Integer

The significand is unpacked as U3.29, then later negated using `h3.xorsign`, to implement round-to-zero semantics as required by GCC.

This implementation chooses to return `INT_MIN` or `INT_MAX` for large exponents, depending on sign. This includes NaNs and infinities.

----
.global __fixsfsi
__fixsfsi:
    h3.bextmi a1, a0, 23, 8
    sltiu a5, a1, 127 + 31
    beqz a5, __fixsfsi_large_exponent
    h3.funpacku3.s a2, a0
    addi a1, a1, -127 - 29
    h3.ssla a2, a2, a1
    h3.xorsign a0, a0, a2
    ret
__fixsfsi_large_exponent:
    srai a0, a0, 31
    li a1, -1
    srli a1, a1, 1
    xor a0, a0, a1
    ret
----

===== Convert Signed Integer to Single-precision

To understand how the exponent is calculated, consider how the integer `1`
will have been normalised. Its Q3 normalisation shift is -29, as the single
set bit should end up in the first integer place in Q3 format. The unbiased
exponent of floating-point `1.f` should be zero, since it's two to the power
zero. The biased exponent is calculated by adding 127 to this value.

Larger values have smaller (i.e. more-positive) normalisation shifts, so
increasing integer values have increasing exponents as we would hope.

----
.global __floatsisf
__floatsisf:
    beqz a0, 1f
    // Normalise to Q3.29; sticky shift helps ensure correct rounding
    h3.feadjq3 a1, a0
    h3.ssrasticky a0, a0, a1
    // Calculate exponent
    addi a1, a1, 127 + 29
    h3.fpackrq3.s a0, a0, a1
1:
    ret
----

===== Convert Unsigned Integer to Single-precision

This is very similar to the previous example, but a logical sticky shift is required to avoid smearing bit 31 of the unsigned integer input. Similarly the U3.29 variant of `h3.feadjq3` is required to get the correct normalisation shift when bit 31 is set.

----
.global __floatunsisf
__floatunsisf:
    beqz a0, 1f
    // Normalise to U3.29; sticky shift helps ensure correct rounding.
    h3.feadju3 a1, a0
    h3.ssrlsticky a0, a0, a1
    // Calculate exponent
    addi a1, a1, 127 + 29
    // Round and pack
    h3.fpackrq3.s a0, a0, a1
1:
    ret
----

===== 64-bit Arithmetic Right Shift

The saturating behaviour of the extended shifts is useful for computing the crossing bits between two registers in a 64-bit integer shift. Shifting right by -32 is equivalent to shifting left by 32, which is all-zeroes. An arithmetic shift is used when the data originates from `a1`, which contains the original sign bit. Shifts originating from `a0` are logical because there is no reason to extend from bit `31`.

----
.global __ashrdi3
__ashrdi3:
    addi a3, a2, -32
    h3.ssra a4, a1, a3
    h3.ssra a1, a1, a2
    h3.ssrl a0, a0, a2
    or a0, a0, a4
    ret
----

A sticky 64-bit shift can be synthesised by collecting sticky bits only in the bottom register. This is useful for shifting the product intermediate in a fused multiply-add where the addend has a greater exponent than the normalised product.

----
.global __ashrdi3_sticky
__ashrdi3_sticky:
    addi a3, a2, -32
    h3.ssrasticky a4, a1, a3
    h3.ssra a1, a1, a2
    h3.ssrlsticky a0, a0, a2
    or a0, a0, a4
    ret
----
